# Generated by Django 4.1.12 on 2023-10-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_attendance_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
