# Generated by Django 4.1.12 on 2023-10-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_attendance_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance',
            new_name='Student',
        ),
    ]
