# Generated by Django 4.1.12 on 2023-10-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_attendance_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
