# Generated by Django 4.1.12 on 2023-10-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_student_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.BigIntegerField()),
                ('data', models.DateField()),
                ('status', models.CharField(default='Absent', max_length=10)),
                ('subject_code', models.IntegerField()),
            ],
        ),
    ]
