# Generated by Django 4.1.12 on 2023-10-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_attendance_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='semester',
            field=models.IntegerField(null=True),
        ),
    ]
