# Generated by Django 4.1.12 on 2023-10-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
